### ISSUE TITLE
crashes when on button is pressed!!

### ISSUE THREAD

**Issue by ghost** [onestraw/sniffer#1]

**Comment by qindeer** [comment]
在编译sniffer.c 时，出现错误：
[新建 Microsoft Word 文档.docx](https://github.com/onestraw/sniffer/files/2686726/Microsoft.Word.docx)

**Comment by qindeer** [comment]
在编译sniffer.c时，出现错误：
![11](https://user-images.githubusercontent.com/43876205/50097708-6adf3700-0255-11e9-9e37-cce4ef8aa481.png)

**Comment by onestraw** [comment]
@qindeer 在根目录调 make

**Comment by qindeer** [comment]
是在上图中文件路径中使用make？？？
应该是怎样的make命令？？？

**Comment by onestraw** [comment]
@qindeer src上一层
